# file: roles/monitoring/tasks/main.yml

- name: Install netdata dependencies
  become: true
  apt: name={{item}} state=present
  with_items:
    - zlib1g-dev
    - uuid-dev
    - libmnl-dev
    - gcc
    - make
    - git
    - autoconf
    - autoconf-archive
    - autogen
    - automake
    - pkg-config
    - curl

- name: Install netdata extras
  become: true
  apt: name={{item}} state=present
  with_items:
    - jq
    - nodejs

- name: Clone netdata repo
  become: true
  shell: cd /opt && git clone https://github.com/firehol/netdata.git --depth=1

- name: Install netdata
  become: true
  shell: cd /opt/netdata && ./netdata-installer.sh

- name: Kill any running netdata processes
  become: true
  shell: killall netdata

- name: Put netdata init.d script
  become: true
  template: src=netdata-init.d.sh dest=/etc/init.d/netdata owner=root group=root mode=0755

- name: Enable netdata service at startup
  become: true
  shell: update-rc.d netdata defaults

- name: Start netdata service
  become: true
  shell: service netdata start