# file: roles/db/tasks/main.yml

- name: Install postgres package
  become: true
  apt: name=postgresql state=present

- name: Create test database
  remote_user: root
  become: true
  become_user: postgres
  postgresql_db: name=test_db login_user=postgres