# file: roles/web/tasks/main.yml

- name: Install nginx
  become: true
  apt:
    name: nginx
    state: present
  
- name: Set custom homepage
  become: true
  template:
    src: index.html
    dest: /var/www/html/index.nginx-debian.html
    owner: root
    group: root
    mode: 0644